# Generated by Django 4.1.2 on 2022-10-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=200)),
                ('temp_min', models.CharField(max_length=200)),
                ('temp_max', models.CharField(max_length=200)),
                ('pressure', models.CharField(max_length=200)),
                ('humidity', models.CharField(max_length=200)),
                ('wind_speed', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
            ],
        ),
    ]
